<section class="reservation-edit">
    <?php 
        $this->headLink()->setStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
//        $this->headScript()->appendFile('/js/helper.js');      
        $form = $this->form;
        $id = $this->id;
        $model = $this->model;
        
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'process',
                'id' => $id,
            ]));
            
        }
        else 
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'process',
            ]));            
        }
        echo $this->form()->openTag($form);        
    ?>
    <h2>Details <?php echo isset($id) ? 'Reservation ID: '. $model->reservation_id : 'New Reservation'?></h2>
    <br>
    <br>
    
    <table class="table">
        <tr>
            <td style="width:100px"><?php echo $this->formLabel($form->get('client_id'))?></td>
            <td>
                <?php echo $this->formElement($form->get('client_id'))?>
                <?php echo $this->formElementErrors($form->get('client_id'))?>
                <a href='' class='ui-button' id='button'>New User</a>
            </td>
        </tr>
        <tr>
            <td colspan="2"> 
                <div class="client-content">Here comes the client content.</div>
            </td>            
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('status_id'))?></td>
            <td>
                <?php echo $this->formElement($form->get('status_id'))?>
                <?php echo $this->formElementErrors($form->get('status_id'))?>
            </td>
        </tr>
    </table>
    <?php echo $this->formElement($form->get('created_at'))?>
    <?php echo $this->formElement($form->get('modified_at'))?>
    <h4>Reserved Entities</h4>
    <?php
        if(isset($model))
        {
            $entities = $model->getReservedEntities($id);
        }
    ?>
    <?php if(!isset($entities) || count($entities) == 0):?>
        <p class="error">There are no reserved entities associated with this reservation!
    <?php else:?>
        <table class="table">
            <tr>
                <th>Room</th>
                <th>Type</th>
                <th>Guest</th>
                <th>Start</th>
                <th>End</th>
                <th>Duration</th>
                <th>Action</th>
            </tr>
            <?php foreach($entities as $entity):?>
            <tr>
                <td><?php echo $entity->guid?></td>
                <td><?php echo $entity->ed_name?></td>
                <td><?php echo $entity->first_name. ' '.$entity->last_name; ?></td>
                <td><?php echo $entity->date_from?></td>
                <td><?php echo $entity->date_to?></td>
                <?php $duration = $entity->getDuration()?>
                <td><?php echo $duration['value'].' '. $duration['type']?></td>
                <td><a href="/pms/reservation/entity/<?php echo $entity->internal_id?>">Edit</a> | <a href="/pms/reservation/deleteEntity/<?php echo $entity->internal_id?>">Delete</a>
            </tr>
            <?php endforeach;?>
        </table>    
    <?php endif;?>    
    <p><a id='addbutton' href="/pms/reservation/entity">Add new entity</a><br>
    <span><?php echo $this->formElement($form->get('submit'))?><a href="/pms/reservation/reset" class='ui-button' id="back_button">Back</a></span>
    <?php echo $this->form()->closeTag()?>     
    <div id="dialog" class="ui-widget"></div>
    <div id="myModalDialog" class='modal fade' role='dialog'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal'>&times;</button>
                    <h4 class='modal-title'>New Client</h4>
                </div>
                <div class='modal-body'></div>
                <div class='modal-footer'>
                    <button type="button" class="btn btn-save" data-dismiss="modal">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>            
        </div>
    </div>
    <script type="text/javascript">
        $(function() {  
            var dialog, formData;
            var fill = function(what) {
                var id = $('select#client_id option:selected').val();
                if(id) 
                {
                    $.get('/pms/client/preview/' + id, function(data) {
                        var client = $(data).find('.client-preview');
                        $('.client-content').html(client); 
                    });    
                }
            };
            
            fill();
                                    
            $("#button").on("click", function(e){
                var fields;
                e.preventDefault();        
                $.get('/pms/client/edit', function(data) {
                   formData = $(data).find('form');                         
                    console.log(formData);
                    $(formData).find('div.buttons').attr('hidden', 'true');
                    $('div.modal-body').html(formData);
                    $("#myModalDialog").find('.modal-body').html(formData);
                    $('#myModalDialog').modal('show');
                });     
            });
            
            $('.btn-save').on('click', function(e) {
                e.preventDefault();
                fields = $(formData).serialize();
                console.log(fields);
                $.post('/pms/ajax/writeNewClient', fields, function(mydata) {                                                
                    var client = mydata.client;
                    var id = client.id;
                    var name = client.first_name + ' ' + client.last_name;
                    $(document).find('#client_id').append('<option value="' + id + '">' + name + '</option>');
                    $(document).find('#client_id').val(id);
                    fill();
                }, "json");     
            });
            
            $('#client_id').on('change', function() {
                  fill();
            }); 
            
            $('#addbutton').on('click', function(e) {
                e.preventDefault();
                var client = $('#client_id').val();
                var status = $('#status_id').val();
                $.get('/pms/ajax/updateReservationModel?client_id=' + client + "&status_id=" + status);
                var href = $(this).attr('href');
                window.location.href = href;
            });
            
            $('form').on('submit', function(e) {
                e.preventDefault();
                var action = $('form').attr('action');
                var postdata = $('form').serialize();
                $.post(action, postdata, function(data) {
                    var formdata = $('form').serialize();                   
                    $.get('/pms/ajax/whereTo', function(data) {
//                        window.location.href = data;
                        var instructions = JSON.parse(data);
                        console.log(instructions);
                        if(instructions.method == 'GET')
                        {
                            $.get(instructions.path, function(data) {
                                $('body').html(data);
                            });                           
                        }
                        else
                        {
                            $.post(instructions.path, instructions.bookmark, function(data) {
                                $('body').html(data);
                            });
                        }
                    });    
                });                
            });
            
            $('#back_button').click(function(evt) {
                evt.preventDefault();
                $.get('/pms/ajax/whereTo', function(data) {                                                                               
                    var instructions = JSON.parse(data);
                    console.log(instructions);
                    if(instructions.method == 'GET')
                    {
                        $.get(instructions.path, function(data) {
                            $('body').html(data);
                        });                           
                    }
                    else
                    {
                        $.post(instructions.path, instructions.bookmark, function(data) {
                            $('body').html(data);
                        });
                    }
                });                
            });
        });
    </script>
    <script src='/js/testajax.js'></script>
    
</section>

