<section class="reservation-entity">
    <?php        
        $this->headLink()->setStylesheet('/js/datetimepicker/jquery.datetimepicker.css');
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');        
        $this->headScript()->appendFile('/js/datetimepicker/build/jquery.datetimepicker.full.js');
                       
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity',
                'id' => $id,
            ]));
        }
        else 
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity'
            ]));    
        }
                
        echo $this->form()->openTag($form);
    ?>
    <h2>Room Reservation Details</h2>
    <dl>
        <dt><?php echo $this->formLabel($form->get('date_from'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('date_from'))?>
            <?php echo $this->formElementErrors($form->get('date_from'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('date_to'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('date_to'))?>
            <?php echo $this->formElementErrors($form->get('date_to'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('entity_definition_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('entity_definition_id'))?>
            <?php echo $this->formElementErrors($form->get('entity_definition_id'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('entity_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('entity_id'))?>            
            <?php echo $this->formElementErrors($form->get('entity_id'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('guest_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('guest_id'))?>
            <?php echo $this->formElementErrors($form->get('guest_id'))?>
            <a href="" id="button" class="ui-button">New</a>
        </dd>
        <dd>
            <?php echo $this->formElement($form->get('submit'))?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag()?>    
    <div id="dialog" title="New Client"></div>
    <script>
    $(function() {
        var dialog, form;
        
        var fillRooms = function() {
            var code = $('#entity_definition_id option:selected').val();
            var date_from = $('#date_from').val();
            var date_to = $('#date_to').val();
            var oldValue, oldText;
            
            if(date_from == "")
            {
                //alert('no value');
            }
            else {
                var id = <?php echo isset($id) ? $id : -1;?>;
                console.log(id);
                oldValue = $('#entity_id').val();            
                oldText = $('#entity_id option[value='+oldValue+']').text();
            }
                        
            $.get('/pms/ajax/getAvailableRooms?from='+date_from+'&to='+date_to+'&type='+code, function(data) {
                var what = JSON.parse(data);
//                dump(what);

                $('#entity_id').empty();
                for(var i in what)
                {
                    $('#entity_id').append($("<option></option>").attr('value', i).text(what[i]));
                }
                
                if(oldText != "")
                {
                    $('#entity_id').append($("<option></option>").attr('value', oldValue).text(oldText));
                    $('#entity_id').val(oldValue);
                }
            });  
        };
        
        fillRooms();
        
        $('.reservation-date').datetimepicker();
        $('.ui-button').button();
        
        $('#entity_definition_id').on('change', function(evt) {
            fillRooms();
        });
        
        dialog = $('#dialog').dialog({
                autoOpen: false,
                modal: true,
                width: 550, 
                height: 630,
                title: "New Guest"
        });
            
        $('#button').on('click', function(e) {
            var formData, fields;
            e.preventDefault();
            $.get('/pms/client/edit', function(data) {
                formData = $(data).find('form table');    
                //$(formData).attr('action', '/pms/client/processFromEntity');
                $(formData).on('submit', function(evt) {
                    evt.preventDefault();
                    fields = $(formData).serialize();                    
                    dialog.dialog('close');    
                    $.post('/pms/ajax/writeNewClient', fields, function(mydata) {     
                        var client = mydata.client;
                        var id = client.id;
                        var name = client.first_name + ' ' + client.last_name;
                        $(document).find('#guest_id').append('<option value="' + id + '">' + name + '</option>');
                        $(document).find('#guest_id').val(id);
                    }, "json");                            
                });
                $(formData).find('.ui-button').button();
                $(dialog).html(formData);                
            });   
                                              
            dialog.dialog('open');                                                 
        });
    });
    </script>
</section>

