<section class="reservation-entity">
    <?php        
        $this->headLink()->setStylesheet('/js/datetimepicker/jquery.datetimepicker.css');
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');        
        $this->headScript()->appendFile('/js/datetimepicker/build/jquery.datetimepicker.full.js');
                       
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity',
                'id' => $id,
            ]));
        }
        else 
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity'
            ]));    
        }
                
        echo $this->form()->openTag($form);
    ?>
    <h2 class='page-header'>Room Reservation Details</h2>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('date_from'))?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('date_from'))?>
        </div>
    </div>
    
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('date_to'))?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('date_to'))?>
        </div>
    </div>
    
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('entity_definition_id'))?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('entity_definition_id'))?>
        </div>
    </div>
    
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('entity_id'))?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('entity_id'))?>
        </div>
    </div>
    
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('guest_id'))?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('guest_id'))?>            
        </div>
        <div class='col-xs-2'>
            <button class='form-control' id='new'>New</button>
        </div>
    </div>
    
    <div class='form-group'>
        <div class='col-xs-offset-2 col-xs-2'>
            <?php echo $this->formElement($form->get('submit'))?>
        </div>
        <div class='col-xs-2'>
            <button class='form-control' id='back'>Back</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag()?>    
    
    <div id="myModalDialog" class='modal fade' role='dialog'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal'>&times;</button>
                    <h4 class='modal-title'>New Client</h4>
                </div>
                <div class='modal-body'></div>
                <div class='modal-footer'>
                    <button type="button" class="btn btn-save" data-dismiss="modal">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>            
        </div>
    </div>
    <script>
    $(document).ready(function() {
        var formData;
        
        var fillRooms = function() {
            var code = $('#entity_definition_id option:selected').val();
            var date_from = $('#date_from').val();
            var date_to = $('#date_to').val();
            var oldValue, oldText;
            
            if(date_from == "")
            {
                //alert('no value');
            }
            else {
                var id = <?php echo isset($id) ? $id : -1;?>;
                console.log(id);
                oldValue = $('#entity_id').val();            
                oldText = $('#entity_id option[value='+oldValue+']').text();
            }
                        
            $.get('/pms/ajax/getAvailableRooms?from='+date_from+'&to='+date_to+'&type='+code, function(data) {
                var what = JSON.parse(data);
//                dump(what);

                $('#entity_id').empty();
                for(var i in what)
                {
                    $('#entity_id').append($("<option></option>").attr('value', i).text(what[i]));
                }
                
                if(oldText != "")
                {
                    $('#entity_id').append($("<option></option>").attr('value', oldValue).text(oldText));
                    $('#entity_id').val(oldValue);
                }
            });  
        };
        
        fillRooms();
        
        $('.reservation-date').datetimepicker();
        $('.ui-button').button();
        
        $('#entity_definition_id').on('change', function(evt) {
            fillRooms();
        });
                                    
        $('#new').on('click', function(e) {
            var fields;
            e.preventDefault();
            $.get('/pms/client/edit', function(data) {
                formData = $(data).find('form');    
                $(formData).find('div.buttons').attr('hidden', 'true');
                $('div.modal-body').html(formData);
                $("#myModalDialog").find('.modal-body').html(formData);
                $('#myModalDialog').modal('show');
            });
        });                                                 
       
        
        $('.btn-save').on('click', function(e) {
            e.preventDefault();
            fields = $(formData).serialize();
            console.log(fields);
            $.post('/pms/ajax/writeNewClient', fields, function(mydata) {        
                console.log(mydata);
                var client = mydata.client;
                var id = client.id;
                var name = client.first_name + ' ' + client.last_name;
                $(document).find('#client_id').append('<option value="' + id + '">' + name + '</option>');
                $(document).find('#client_id').val(id);
                //fill();
            }, "json");    
        });
        
        $('#back').on('click', function(e) {
            e.preventDefault();
            window.location.href='/pms/reservation/edit';
        });
    });
    </script>
</section>

