<section class="reservation-entity">
    <?php        
        $this->headLink()->setStylesheet('/js/datetimepicker/jquery.datetimepicker.css');
        $this->headScript()->appendFile('/js/datetimepicker/build/jquery.datetimepicker.full.js');
        $this->headScript()->appendFile('/js/helper.js');      
                
        $form = $this->form;
        $id = $this->id;
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity',
                'id' => $id,
            ]));
        }
        else 
        {
            $form->setAttribute('action', $this->url('pms/reservation', [
                'action' => 'processEntity'
            ]));    
        }
                
        echo $this->form()->openTag($form);
    ?>
    <h2>Room Reservation Details</h2>
    <dl>
        <dt><?php echo $this->formLabel($form->get('date_from'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('date_from'))?>
            <?php echo $this->formElementErrors($form->get('date_from'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('date_to'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('date_to'))?>
            <?php echo $this->formElementErrors($form->get('date_to'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('entity_definition_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('entity_definition_id'))?>
            <?php echo $this->formElementErrors($form->get('entity_definition_id'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('entity_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('entity_id'))?>
            <?php echo $this->formElementErrors($form->get('entity_id'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('guest_id'))?><dt>
        <dd>
            <?php echo $this->formElement($form->get('guest_id'))?>
            <?php echo $this->formElementErrors($form->get('guest_id'))?>
        </dd>
        <dd>
            <?php echo $this->formElement($form->get('submit'))?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag()?>
</section>

