<section class="reservation-index">
    <?php
        $reservations = $this->reservations;
    ?>
    <h2>Reservations</h2>
    <?php if(count($reservations) == 0):?>
        <p class="error">No current reservations!
    <?php else: ?>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Client</th>
                <th>Created Ad</th>
                <th>Modified At</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        <?php foreach($reservations as $reservation):?>
            <tr>
                <td><?php echo $reservation['reservation_id']?></td>
                <td><?php echo $reservation['first_name'].' '.$reservation['last_name']?></td>
                <td><?php echo $reservation['created_at']?></td>
                <td><?php echo $reservation['modified_at']?></td>
                <td><?php echo $reservation['statustext']?></td>
                <td><a href="/pms/reservation/edit/<?php echo $reservation['id']?>">Edit</a>&nbsp;|&nbsp;<a href="/pms/reservation/delete/<?php echo $reservation['id']?>">Delete</a></td>
            </tr>
        <?php endforeach;?>
        </table>
    <?php endif;?>
        <a href="/pms/reservation/edit">Add new</a>&nbsp;|&nbsp;<a href='/pms/admin'>Home</a>&nbsp;|&nbsp;<a href="/pms/entity/fullList?id=22&sort=guid&startDate=<?php echo date('Y-m-d', time());?>">Check Avalability >>> </a> 
</section>

