<section class="reservation-index">
    <?php
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headLink()->appendStylesheet('/tablesorter-master/css/theme.metro-dark.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.js');
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.widgets.js');
        $this->headScript()->appendFile('/tablesorter-master/js/widgets/widget-scroller.js');
        
        $reservations = $this->reservations;
    ?>
    <h2>Reservations</h2>
    <?php if(count($reservations) == 0):?>
        <p class="error">No current reservations!
    <?php else: ?>
        <table class="table tablesorter">
            <thead>
            <tr>
                <th>ID</th>
                <th>Client</th>
                <th>Created Ad</th>
                <th>Modified At</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
        <?php foreach($reservations as $reservation):?>
            <tr>
                <td><?php echo $reservation['reservation_id']?></td>
                <td><?php echo $reservation['first_name'].' '.$reservation['last_name']?></td>
                <td><?php echo $reservation['created_at']?></td>
                <td><?php echo $reservation['modified_at']?></td>
                <td><?php echo $reservation['statustext']?></td>
                <td><a href="/pms/reservation/edit/<?php echo $reservation['id']?>">Edit</a>&nbsp;|&nbsp;<a href="/pms/reservation/delete/<?php echo $reservation['id']?>">Delete</a></td>
            </tr>
        <?php endforeach;?>
            </tbody>
        </table>
    <?php endif;?>
        <a href="/pms/reservation/edit">Add new</a>&nbsp;|&nbsp;<a href='/'>Home</a>&nbsp;|&nbsp;<a href="/pms/entity/fullList">Check Availability >>> </a> 
</section>
<script>
    $(document).ready(function(){
       $('.tablesorter').tablesorter({
            theme: 'metro-dark',
            showProcessing: true,
            headerTemplate : '{content} {icon}',
            widgets: [ 'columns', 'stickyHeaders', 'scroller' ],
            widgetOptions : {
                    scroller_height : 400,
                    // scroll tbody to top after sorting
                    scroller_upAfterSort: true,
                    // pop table header into view while scrolling up the page
                    scroller_jumpToHeader: true,
                    // In tablesorter v2.19.0 the scroll bar width is auto-detected
                    // add a value here to override the auto-detected setting
                    scroller_barWidth : null
                    // scroll_idPrefix was removed in v2.18.0
                    // scroller_idPrefix : 's_'
            }
        });
    });
</script>

