<section class="entity-edit">
    <?php 
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-2.1.4.js');        
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
        
        $form = $this->form;
        $id = $this->id;
        $attributes = $this->attributes;
        $definitionId = $form->get('definition_id')->getValue();        
        
        if(isset($this->id))
        {
            $form->setAttribute('action', $this->url('pms/entity', [
                'action' => 'process',
                'id' => $this->id,
            ]));
        }
        else 
        {
            $form->setAttribute('action', $this->url('pms/entity', [
                'action' => 'process',
            ]));
        }
        
        echo $this->form()->openTag($form);
    ?>    
    <h3>Object Details</h3>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('definition_id')) ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('definition_id'));?>
        </div>
    </div>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('guid')) ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('guid'));?>
        </div>
    </div>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('status_id')) ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('status_id'));?>
        </div>
    </div>
    <?php if(count($attributes) > 0): ?>
        <?php foreach ($attributes as $attribute):?>
            <?php
                switch($attribute->type) {
                    case 'textarea':
                        $width_class = 'col-xs-10';
                        break;
                    case 'text':
                        $width_class = 'col-xs-10';
                        break;
                    case 'boolean':
                        $width_class = 'col-xs-1';
                        break;
                    case 'integer':
                        $width_class = 'col-xs-2';
                        break;
                    case 'double':
                        $width_class = 'col-xs-2';
                        break;       
                    case 'select':
                        $width_class = 'col-xs-4';
                        break; 
                    default:
                        $width_class = 'col-xs-4';
                        break;
                }
            ?>            
            <div class="form-group">
                <?php echo $this->formLabel($form->get($attribute->code))?>
                <div class="<?php echo $width_class?>">
                    <?php echo $this->formElement($form->get($attribute->code))?>
                </div> 
            </div>            
        <?php endforeach;?>    
    <?php endif;?>    
    <div class="form-group">
        <label class="control-label col-xs-2" for="att-table">Parameters</label>
        <div class="col-xs-10"  id="attribute-content"></div>
    </div>
    <div class='form-group'>
        <div class='col-xs-offset-2 col-xs-2'>
            <?php echo $this->formElement($form->get('submit'));?>
        </div>
        <div class='col-xs-2'>
            <button id='back' class='form-control'>Back</button>
        </div>
    </div>
    
    <?php echo $this->form()->closeTag();?>
</section>
<script>
$(document).ready(function(){
    $('button#back').on('click', function(e) {
        window.location.href = '/pms/entity';
    });
    var id = <?php echo $definitionId;?>;
    $.get('/pms/entity-definition/preview/' + id, function(data) {
        var table = $(data).find('table');
         $('div#attribute-content').html(table); 
     });
});
</script>
