<section class="entity-edit">
    <?php 
        $this->headScript()->appendFile('/js/jquery-2.1.4.js');
        $this->headScript()->appendFile('/js/helper.js');        
        
        $form = $this->form;
        $id = $this->id;
        $attributes = $this->attributes;
        
        if(isset($this->id))
        {
                $form->setAttribute('action', $this->url('pms/entity', [
                    'action' => 'process',
                    'id' => $this->id,
                ]));
        }
        else 
        {
                $form->setAttribute('action', $this->url('pms/entity', [
                    'action' => 'process',
                ]));
        }
        
        echo $this->form()->openTag($form);
    ?>
    <h3>Object Details</h3>
    <dl>        
        <dt><?php echo $this->formLabel($form->get('definition_id')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('definition_id'));?>
            <?php echo $this->formElementErrors($form->get('definition_id'));?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('guid')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('guid'));?>
            <?php echo $this->formElementErrors($form->get('guid'));?>
        </dd>
<!--        <dt><?php echo $this->formLabel($form->get('status')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('status'));?>
            <?php echo $this->formElementErrors($form->get('status'));?>
        </dd>-->
        <dt><?php echo $this->formLabel($form->get('status_id')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('status_id'));?>
            <?php echo $this->formElementErrors($form->get('status_id'));?>
        </dd>
        <?php if(isset($attributes)):?>
            <?php foreach($attributes as $attribute):?>
                <dt><?php echo $this->formLabel($form->get($attribute->code)) ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get($attribute->code));?>
                    <?php echo $this->formElementErrors($form->get($attribute->code));?>
                </dd>
            <?php endforeach;?>
        <?php endif;?>
        <dd>
            <?php echo $this->formElement($form->get('submit'));?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag();?>
    <div class="attribute-content"></div>   
</section>
