<section class="entity">
    <?php 
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');    
        $entities = $this->entities;
    ?>
    <h2>Available Objects</h2>
    <?php if(count($entities) == 0):?>
        <p class="error">There are no rooms in the facility.
    <?php else: ?>
        <table class="table">
            <tr>
                <th>Room Nr.</th>
                <th>Room Type</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            <?php foreach($entities as $entity):?>
                <tr>
                    <td><?php echo $entity['guid']?></td>
                    <td><?php echo $entity['code']?></td>
                    <td><?php echo $entity['SValue']?></td>
                    <td><a href="/pms/entity/edit/<?php echo $entity['id']?>">Edit</a> | <a href="/pms/entity/delete/<?php echo $entity['id'] ?>">Delete</a>                        
                </tr>
            <?php endforeach;?>
        </table>
    <?php endif;?>
    <a href="/pms/entity/new">Add new</a> | <a href='/'>Home</a>
    <div hidden="true" id="dialog-confirm" title="Delete entity?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0"></span>Entity will be completely deleted and cannot be recovered. Are you sure?</p>
    </div>
</section>
<script>
$(function() {
   $('.delete').on('click', function(evt) {
        evt.preventDefault();
        console.log(evt.target);
        val address =  $(evt.target).attr('href').val();
        alert(address);
        
//        $('#dialog-confirm').dialog({
//            resizable: false,
//            height: 250,
//            width: 350,
//            modal: true,
//            buttons: {
//                "Delete" : function() {
//                    $(this).dialog("close");
//                },
//                Cancel: function() {
//                    $(this).dialog('close');
//                }
//            }
//       });
        
   });
});
</script>

