<section class="entity">
    <?php 
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headLink()->appendStylesheet('/tablesorter-master/css/theme.metro-dark.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.js');
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.widgets.js');
        $this->headScript()->appendFile('/tablesorter-master/js/widgets/widget-scroller.js');
        $entities = $this->entities;
    ?>
    <h2>Available Objects</h2>
    <?php if(count($entities) == 0):?>
        <p class="error">There are no rooms in the facility.
    <?php else: ?>
        <table class="table tablesorter">
            <thead>
                <tr>
                    <th>Object Nr.</th>
                    <th>Object Type</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($entities as $entity):?>
                    <tr>
                        <td><?php echo $entity['guid']?></td>
                        <td><?php echo $entity['code']?></td>
                        <td><?php echo $entity['SValue']?></td>
                        <td><a href="/pms/entity/edit/<?php echo $entity['id']?>">Edit</a> | <a id='delete' href="/pms/entity/delete/<?php echo $entity['id'] ?>">Delete</a>                        
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    <?php endif;?>
    <a href="/pms/entity/new">Add new</a> | <a href='/'>Home</a>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Delete Object</h4>
                </div>
                <div class="modal-body">
                    <p>Object will be completely deleted and cannot be recovered. Are you sure?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-confirm" data-dismiss="modal">Yes</button>
                    <button type="button" class="btn btn-cancel" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
$(document).ready(function() {
    var path;
    $('.tablesorter').tablesorter({
            theme: 'metro-dark',
            showProcessing: true,
            headerTemplate : '{content} {icon}',
            widgets: [ 'columns', 'stickyHeaders', 'scroller' ],
            widgetOptions : {
                    scroller_height : 400,
                    // scroll tbody to top after sorting
                    scroller_upAfterSort: true,
                    // pop table header into view while scrolling up the page
                    scroller_jumpToHeader: true,
                    // In tablesorter v2.19.0 the scroll bar width is auto-detected
                    // add a value here to override the auto-detected setting
                    scroller_barWidth : null
                    // scroll_idPrefix was removed in v2.18.0
                    // scroller_idPrefix : 's_'
            }
    });              
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        //console.log(path);
        $('#myModal').modal('show');
    });
    
    $('.btn-confirm').on('click', function(e) {        
        //alert(path);
        window.location.href = path;
    });
});
</script>

