<section class="entity-type-edit">
    <?php 
        $this->headStyle()->appendStyle('footer', 'clear: both');
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js'); 
        
        $id = $this->id;
        $form = $this->form;
        $model = $this->model;
        if($id)
        {
            $id = (int)$id;
            $form->setAttribute('action', $this->url('pms/entity-type', [                
                'action' => 'process',
                'id' => $id,
            ]));
        }
        else {
            $form->setAttribute('action', $this->url('pms/entity-type', [
                'action' => 'process',
            ]));
        }        
        echo $this->form()->openTag($form);
    ?>

    <?php if(!$id):?>
    <h2 class="page-header">New Object Type</h2>
    <?php else:?>
    <h2 class='page-header'>Change '<?php echo $model->name?>' details</h2>
    <?php endif;?>
    
    <?php echo $this->formElement($form->get('user_id'))?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name'))?>
        <div class="col-xs-5">
            <?php echo $this->formElement($form->get('name'))?>
        </div> 
    </div>
    
    <div class="form-group">
        <?php echo $this->formLabel($form->get('description'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('description'))?>
        </div> 
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('time_resolution'))?>
        <div class="col-xs-2">
            <?php echo $this->formElement($form->get('time_resolution'))?>
        </div> 
    </div>
    <div class="form-group">
        <label class="control-label col-xs-2" for="myTable">Parameters</label>
        <div class="col-xs-10">
            <?php if(isset($model->attributes)):?>
            <table id='myTable' class='table'>
                <tr>
                    <th>Parameter</th>
                    <th>Accessibility</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
                <?php foreach($model->attributes as $attribute):?>
                <tr>
                    <td><?php echo $attribute->label?></td>
                    <td><?php 
                        $values = ['GLOBAL', 'DEFINITION', 'OBJECT'];
                        echo $values[$attribute->scope];
                    ?></td>
                    <td><?php echo $attribute->type?></td>
                    <td>
                        <a href='/pms/entity-type/editAttribute/<?php echo $attribute->internal_id?>'>Edit</a> 
                        | 
                        <a href='/pms/entity-type/deleteAttribute/<?php echo $attribute->internal_id?>'>Delete</a>
                    </td>
                </tr>
                <?php endforeach;?>
            </table>  
            <?php else:?>
            <p>No defined parameters</p>
            <?php endif;?>
        </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-2">
            <?php echo $this->formElement($form->get('submit'))?>
        </div> 
       <div class="col-xs-2">
            <button id="back" class="form-control">Back</button>
       </div> 
        <div class='col-xs-2'>
            <button id='new' class='form-control'>New Parameter</button>
        </div>
    </div>
</section>
<script>
$(document).ready(function() {
    $('button#new').on('click', function(e) {
        e.preventDefault();         
        var formData = $('form').serialize();
        console.log(formData);
        // remember first
        $.post('/pms/ajax/rememberEntityType', formData, function(data) {
            console.log(data);
        });        
        window.location.href='/pms/entity-type/editAttribute';
    });
});
</script>

