<section class="entity-type-edit-attribute">
    <?php 
        $this->headScript()->appendFile('/js/jquery-2.1.4.js');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
        $this->headScript()->appendFile('/js/forms.js');   
        $id = $this->id;
        $form = $this->form;
        $model = $this->model;
        $type = $this->type;
        $typeId = $type->id;
        
        if($id)
        {            
            $id = (int)$id;
            $form->setAttribute('action', $this->url('pms/entity-type', [                
                'action' => 'processEditAttribute',
                'id' => $id,
            ]));
        }
        else {
            $form->setAttribute('action', $this->url('pms/entity-type', [
                'action' => 'processEditAttribute',
            ]));
        }        
        echo $this->form()->openTag($form);
        // Invisible field.
        echo $this->formElement($form->get('counter'));
    ?>
    <?php $this->headScript()->captureStart();?>
        $(document).ready(function(evt) {
            var model = <?php 
                if(isset($model))
                {
                    echo json_encode($model);
                }
                else 
                {
                    echo json_encode("No Model!");
                }            
            ?>;
            initEntries(model);
        });
    <?php $this->headScript()->captureEnd();?>
    <?php if(!$id):?>
    <h2>New Parameter</h2>
    <?php else:?>
    <h2>Change '<?php echo $model->label?>' details</h2>
    <?php endif;?>
    <dl>
        <div class='form-group'>
            <?php echo $this->formLabel($form->get('code')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('code')) ?>
                <?php echo $this->formElementErrors($form->get('code'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('scope')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('scope')) ?>
                <?php echo $this->formElementErrors($form->get('scope'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('label')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('label')) ?>
                <?php echo $this->formElementErrors($form->get('label'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('type')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('type')) ?>
                <?php echo $this->formElementErrors($form->get('type'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('unit')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('unit')) ?>
                <?php echo $this->formElementErrors($form->get('unit'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('sort_order')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('sort_order')) ?>
                <?php echo $this->formElementErrors($form->get('sort_order'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('unique')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('unique')) ?>
                <?php echo $this->formElementErrors($form->get('unique'))?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('nullable')) ?>
            <div class="col-xs-10">
                <?php echo $this->formElement($form->get('nullable')) ?>
                <?php echo $this->formElementErrors($form->get('nullable'))?>
            </div>      
        </div>
        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-2">
                <?php echo $this->formElement($form->get('submit')) ?>                               
            </div>
            <div class="col-xs-2">
                <button type="button" id='back' class="btn btn-default form-control">Back</button>
            </div> 
        </div>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>
<script>
$(document).ready(function() {
    $('button#back').on('click', function(e) {
        e.preventDefault();
        var loc = '/pms/entity-type/edit/' + <?php echo json_encode(isset($typeId) ? $typeId : '') ?>;
        window.location.href = loc;
    });
});
</script>


