<section class="entity-type">
    <?php
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
        $types = $this->types;
    ?>
    <?php if($types == null || count($types) == 0):?>
        <h2>Configuration required</h2>
        <p class="error">There are currently no defined object types.</p>
    <?php else:?>
        <h2>Object Types</h2>
        <p>
        <p>
        <table class="table">
            <tr>
<!--                <th>ID</th>-->
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        <?php foreach($types as $type):?>
            <tr>
<!--                <td>
                    <?php echo $type['id'] ?>
                </td>-->
                <td>
                    <?php echo $type['name'] ?>
                </td>
                <td>
                    <?php echo $type['description'] ?>
                </td>
                <td>
                    <a href="/pms/entity-type/edit/<?php echo $type['id']?>">Edit</a> | <a id='delete' href="/pms/entity-type/delete/<?php echo $type['id']?>">Delete</a>
                </td>
            </tr>
        <?php endforeach;?>
        </table>
    <?php endif; ?>
    <a href="/pms/entity-type/new">Add new object type</a> | <a href='/'>Home</a>
    <div hidden="true" id="ConfirmDialog" title="Delete Entity Type?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0; font-size: 0.75em"></span>Type will be completely deleted and cannot be recovered. Are you sure?</p>
    </div>
</section>
<script>
$(document).ready(function() {
    var path;
    $('#ConfirmDialog').dialog({
        resizable: false,
        height:200,
        width:400,
        modal:true,
        autoOpen: false,
        modal:true,
        buttons : {
            "Yes" : function() {                
                $(this).dialog('close');             
                window.location.href = path;
            },
            "No" : function() {
                $(this).dialog('close');             
            }
        },
        close : function() {
            $(this).dialog('close');
        }
    });    
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        console.log(path);
        $('#ConfirmDialog').dialog('open');
    });
});
</script>



