<section class="entity-type">
    <?php
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
        $types = $this->types;
    ?>
    <?php if($types == null || count($types) == 0):?>
        <h2>Configuration required</h2>
        <p class="error">There are currently no defined object types.</p>
    <?php else:?>
        <h2>Object Types</h2>
        <p>
        <p>
        <table class="table">
            <tr>
<!--                <th>ID</th>-->
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        <?php foreach($types as $type):?>
            <tr>
<!--                <td>
                    <?php echo $type['id'] ?>
                </td>-->
                <td>
                    <?php echo $type['name'] ?>
                </td>
                <td>
                    <?php echo $type['description'] ?>
                </td>
                <td>
                    <a href="/pms/entity-type/edit/<?php echo $type['id']?>">Edit</a> | <a id='delete' href="/pms/entity-type/delete/<?php echo $type['id']?>">Delete</a>
                </td>
            </tr>
        <?php endforeach;?>
        </table>
    <?php endif; ?>
    <a href="/pms/entity-type/new">Add new object type</a> | <a href='/'>Home</a>
    <div hidden="true" id="ConfirmDialog" title="Delete Entity Type?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0; font-size: 0.75em"></span>Type will be completely deleted and cannot be recovered. Are you sure?</p>
    </div>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Delete Object Type</h4>
                </div>
                <div class="modal-body">
                    <p>Object type will be completely deleted and cannot be recovered. Are you sure?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-confirm" data-dismiss="modal">Yes</button>
                    <button type="button" class="btn btn-cancel" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
$(document).ready(function() {
    var path;    
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        console.log(path);
        //$('#ConfirmDialog').dialog('open');
        $('#myModal').modal('show');
    });    
    
    $('.btn-confirm').on('click', function(e) {        
        //alert(path);
        window.location.href = path;
    });
});
</script>



