<section class="entity-type">
    <?php
        $types = $this->types;
    ?>
    <?php if($types == null || count($types) == 0):?>
        <h2>Configuration required</h2>
        <p class="error">There are currently no defined object types.</p>
    <?php else:?>
        <h2>Object Types</h2>
        <p>
        <p>
        <table class="table">
            <tr>
<!--                <th>ID</th>-->
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        <?php foreach($types as $type):?>
            <tr>
<!--                <td>
                    <?php echo $type['id'] ?>
                </td>-->
                <td>
                    <?php echo $type['name'] ?>
                </td>
                <td>
                    <?php echo $type['description'] ?>
                </td>
                <td>
                    <a href="/pms/entity-type/edit/<?php echo $type['id']?>">Edit</a> | <a href="/pms/entity-type/delete/<?php echo $type['id']?>">Delete</a>
                </td>
            </tr>
        <?php endforeach;?>
        </table>
    <?php endif; ?>
    <a href="/pms/entity-type/new">Add new object type</a> | <a href='/'>Home</a>
</section>



