<section class='business-edit'>
    <?php 
        $form = $this->form;
        $form->setAttribute('action', $this->url('pms/business', [
            'action' => 'process'
        ]));
        echo $this->form()->openTag($form);
    ?>
    <h2 class="page-header">Change business data</h2>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('name'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('description'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('description'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('company_name'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('company_name'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('company_name'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('company_name'))?>
        </div>
    </div>
 
    <div class="form-group">
        <?php echo $this->formLabel($form->get('address'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('address'))?>
        </div>
    </div>
    
    <div class="form-group">
        <?php echo $this->formLabel($form->get('phone'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('phone'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('email'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('email'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('contact_first_name'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('contact_first_name'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('contact_last_name'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('contact_last_name'))?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-2">
            <?php echo $this->formElement($form->get('submit'))?>
        </div>
        <div class="col-xs-2">
            <button class="form-control" id='back'>Back</button>
        </div>
    </div>        
    <?php echo $this->form()->closeTag();?>    
</section>
<script>
$(document).ready(function(){
    $('#back').on('click', function(e) {
        window.location.href = '/pms/business';
    });
});
</script>
