<section class="login-admin">
    <?php
        $user = $this->username;
    ?>
    <h1>
        Welcome <?php echo $user?> :)!
    </h1>
    <p>As the member of ADMIN group, you can choose to do following things...
    <h3>Define Business</h3>
    Here you can/should define your type of business. <a href='/pms/business'>Define business</a>
    <h3>Object Type Management</h3>
    <p>Object types are the basic prototypes of reservation process objects, which are going to be dealt with in this presentation.
        You can add new ones or edit existing ones, or eventually delete them. <p><p><a href="/pms/entity-type">To object type management >>> </a>
    <h3>Object Definition Management</h3>
    <p>Object types are further split to the subtypes, which are fitted to the potential client needs. These subtypes are called 'object definitions'
       and except the basic set of parameters, can have an arbitrary set of parameters which can be added and deleted by you. This will be explained 
       by example: if an 'object type' is a room, an 'object definition' would be what kind of room it is - single, double, suite, de louxe single etc.
       By defining a set of parameters and setting of their values, you make the different entity definitions. In this section you can add the new ones
       and edit or delete existing ones. <p><p><a href='/pms/entity-definition'>To object definitions management >>> </a>
    <h3>Object Management</h3>
    Object is the final subject of our actions. It can be anything which can be reserved and used on defined period of time - hotel room, conference room,
    office, gym, sport field, boat etc. Objects are defined by the object definitions and inherit of of their properties, having also some of their own, like 
    <i>guid</i> and <i>status</i> properties, which help them differ one from another. You could define some of the parameters which are specific only to a particular 
    entity. Example: Room 101 is single room, which means that it can receive max one person, it has bathroom, AC and TV appliances. But it could have a 'sea view' or 'rare view', 
    which is not defined by a room definition. This property is specific to this particular room. <p><p><a href='/pms/entity'>On to object management >>> </a>
        <a href="/pms/entity/fullList">Current Availability >>></a>
    <h3>Reservations</h3>
    Here, you can make reservations. <a href='/pms/reservation'>Go to reservation page >>>> </a>    
    <h3>Attribute Management</h3>
    <p>Attributes are the parameter objects which can be associated with the different entity definitions or entities. An attribute basically consists name, 
        datatype and value. Here, you can add new and edit or delete the existing ones. <p><p><a href='/pms/attribute-manager'>To attribute management >>> </a>
    <h3>User Management</h3>
    <p>As administrator, you have the possibility to add and delete the application users. <p><p><a href='/pms/user-manager'>To user management >>>> </a>
    <h3>Client Management</h3>
    <p>The clients list. As administrator, you shouldn't be dealing with it, but currently, until we define other users, it's here. 
    <p><p><a href='/pms/client'>To client preview and management >>>> </a>    
</section>
