<section class="login">
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, ['controller' => 'login', 'action' => 'process']));
        echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd>
            <?php 
                echo $this->formElement($form->get('email')); 
                echo $this->formElementErrors($form->get('email')); 
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
        <dd>
            <?php 
                echo $this->formElement($form->get('password')); 
                echo $this->formElementErrors($form->get('password')); 
            ?>
        </dd>
        <dd>
            <?php 
                echo $this->formElement($form->get('submit')); 
                echo $this->formElementErrors($form->get('submit')); 
            ?>
        </dd>
    </dl>
    <?php $this->form()->closeTag();?>
</section>


