<section class="login-user">
    <?php
        $user = $this->username;
    ?>
    <h1>
        Welcome <?php echo $user?> :)!
    </h1>
    <p>As the user of the system, you can do following...
    <h3>Make Reservations</h3>
    Here, you can make reservations. <a href='/pms/reservation'>Go to reservation page >>>> </a>    
    <h3>Manage the client list</h3>
    <p>The clients list. As administrator, you shouldn't be dealing with it, but currently, until we define other users, it's here. 
    <p><p><a href='/pms/client'>To client preview and management >>>> </a>    
</section>
