<section class="reports-complete" style="height: 100%;">
<?php
    $usageData = $this->usageData;
    $header = $usageData['header'];
    unset($usageData['header']);
    ksort($usageData);
    $form = $this->form;    
    $form->setAttribute('action', $this->url(NULL, [
        'controller' => 'reports',
        'action' => 'completeUsage', 
    ]));
?>
    <div id="form-container">
        <h2>Search</h2>
        <?php echo $this->form()->openTag($form);?>
            <?php echo $this->formLabel($form->get('type'))?>
            <?php echo $this->formElement($form->get('type'))?>
            <?php echo $this->formLabel($form->get('start'))?>
            <?php echo $this->formElement($form->get('start'))?>
            <?php echo $this->formLabel($form->get('end'))?>
            <?php echo $this->formElement($form->get('end'))?>
            <?php echo $this->formElement($form->get('submit'))?>
        <?php echo $this->form()->closeTag();?>
    </div>
    <div id="results-container">            
        <h3><?php echo $header['type']?> Object usage 
            <?php if(isset($header['from'])) echo 'for the period from <i><u>'.$header['from'];?></u></i>
            <?php if(isset($header['to'])) echo ' to <i><u>'.$header['to'];?></u></i>
        </h3>    
        <p>
        <table class="table">
            <thead>
                <tr>
                    <th>Number</th>
                    <th>Code</th>
                    <th>Object</th>
                    <th>Duration</th>
                    <th>Unit</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($usageData as $usage):?>
                <tr>
                    <td><?php echo $usage['guid']?></td>
                    <td><?php echo $usage['code']?></td>
                    <td><?php echo $usage['name']?></td>
                    <td><?php echo $usage['duration']?></td>
                    <td><?php echo $usage['unit']?></td>
                    <td><a href="/pms/reports/entityUsage?id=<?php echo $usage['entity_id']?>">See Details</a></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</section>
<style>
    #form-container {
        border: 1px solid #aaaaaa;
        border-radius: 10px;
        width: 100%;
        height: 100px;
        display: block;
        box-shadow: 2px 2px #333333;
        padding-left: 10px;
    }
    #results-container {
        width: 100%;
        display: block;
    }
</style>
