<section class="reports-complete" style="height: 100%;">
<?php
$this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
    $this->headLink()->appendStylesheet('/tablesorter-master/css/theme.metro-dark.css');
    $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
    $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.js');
    $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.widgets.js');
    $this->headScript()->appendFile('/tablesorter-master/js/widgets/widget-scroller.js');
    
    $usageData = $this->usageData;
    $header = $usageData['header'];
    unset($usageData['header']);
    ksort($usageData);
    $form = $this->form;    
    $form->setAttribute('action', $this->url(NULL, [
        'controller' => 'reports',
        'action' => 'completeUsage', 
    ]));
    if(!empty($this->start))
    {
        $start = $this->start;
    }
    if(!empty($this->end))
    {
        $end = $this->end;
    }        
?>
    <div class="well">
        <h2>Search</h2>
        <?php echo $this->form()->openTag($form);?>
            <?php echo $this->formLabel($form->get('type'))?>
            <?php echo $this->formElement($form->get('type'))?>
            <?php echo $this->formLabel($form->get('start'))?>
            <?php echo $this->formElement($form->get('start'))?>
            <?php echo $this->formLabel($form->get('end'))?>
            <?php echo $this->formElement($form->get('end'))?>
            <?php echo $this->formElement($form->get('submit'))?>
        <?php echo $this->form()->closeTag();?>
    </div>
    <div class='well'>            
        <h3><?php echo $header['type']?> Object usage 
            <?php if(isset($header['from'])) echo 'for the period from <i><u>'.$header['from'];?></u></i>
            <?php if(isset($header['to'])) echo ' to <i><u>'.$header['to'];?></u></i>
        </h3>    
        <p>
        <table class="table">
            <thead>
                <tr>
                    <th>Number</th>
                    <th>Code</th>
                    <th>Object</th>
                    <th>Duration</th>
                    <th>Unit</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($usageData as $usage):?>
                <tr>
                    <td><?php echo $usage['guid']?></td>
                    <td><?php echo $usage['code']?></td>
                    <td><?php echo $usage['name']?></td>
                    <td><?php echo $usage['duration']?></td>
                    <td><?php echo $usage['unit']?></td>
                    <?php $argString = 'id='.$usage['entity_id'];
                        if(isset($start))
                        {
                            $argString .= '&start='.$start;
                        }
                        if(isset($end))
                        {
                            $argString .= '&end='.$end;
                        }
                    ?>                    
                    <td><a href="/pms/reports/entityUsage?<?php echo $argString?>">See Details</a></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</section>
<script>
    $(document).ready(function() {
        $('.tablesorter').tablesorter({
            theme: 'metro-dark',
            showProcessing: true,
            headerTemplate : '{content} {icon}',
            widgets: [ 'columns', 'stickyHeaders', 'scroller' ],
            widgetOptions : {
                    scroller_height : 400,
                    // scroll tbody to top after sorting
                    scroller_upAfterSort: true,
                    // pop table header into view while scrolling up the page
                    scroller_jumpToHeader: true,
                    // In tablesorter v2.19.0 the scroll bar width is auto-detected
                    // add a value here to override the auto-detected setting
                    scroller_barWidth : null
                    // scroll_idPrefix was removed in v2.18.0
                    // scroller_idPrefix : 's_'
            }
        });
    });
</script>
<style>
    #form-container {
        border: 1px solid #aaaaaa;
        border-radius: 10px;
        width: 100%;
        height: 100px;
        display: block;
        box-shadow: 2px 2px #333333;
        padding-left: 10px;
    }
    #results-container {
        width: 100%;
        display: block;
    }
</style>
