<section class="entity-definition-edit">
    <?php 

        $id = $this->id;
        $form = $this->form;
        $attributes = $this->attributes;
        
        if($id)
        {
            $id = (int)$id;
            $form->setAttribute('action', $this->url('pms/entity-definition', [                
                'action' => 'process',
                'id' => $id,
            ]));
        }
        else {
            $form->setAttribute('action', $this->url('pms/entity-definition', [
                'action' => 'process',
            ]));
        }        
        echo $this->form()->openTag($form);
    ?>
    <?php if(!$id):?>
    <h2>New object definition</h2>
    <?php else:?>
    <h2>Change object details</h2>
    <?php endif;?>
    <dl>
        <dt><?php echo $this->formLabel($form->get('entity_type_id')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('entity_type_id')) ?>
            <?php echo $this->formElementErrors($form->get('entity_type_id'))?>
        </dd>        
        <dt><?php echo $this->formLabel($form->get('code')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('code')) ?>
            <?php echo $this->formElementErrors($form->get('code'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('name')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('name')) ?>
            <?php echo $this->formElementErrors($form->get('name'))?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('description')) ?></dt>
        <dd>
            <?php echo $this->formElement($form->get('description')) ?>
            <?php echo $this->formElementErrors($form->get('description'))?>
        </dd>
        <?php if(count($attributes) > 0): ?>
            <?php foreach ($attributes as $attribute):?>
                <dt><?php echo $this->formLabel($form->get($attribute->code)) ?></dt>
                <dd>
                    <?php echo $this->formElement($form->get($attribute->code)) ?>
                    <?php echo $this->formElementErrors($form->get($attribute->code))?>
                </dd>
            <?php endforeach;?>
        <?php endif;?>        
        <dd>
            <?php echo $this->formElement($form->get('submit')) ?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
    <a href="/pms/attribute-manager/edef/<?php echo $this->id ?>">Edit attributes</a>
</section>

