<section class="entity-definition-edit">
    <?php 
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');      
        
        $id = $this->id;
        $form = $this->form;
        $attributes = $this->attributes;
        
        if($id)
        {
            $id = (int)$id;
            $form->setAttribute('action', $this->url('pms/entity-definition', [                
                'action' => 'process',
                'id' => $id,
            ]));
        }
        else {
            $form->setAttribute('action', $this->url('pms/entity-definition', [
                'action' => 'process',
            ]));
        }        
        echo $this->form()->openTag($form);
    ?>
    <?php if(!$id):?>
    <h2>New object definition</h2>
    <?php else:?>
    <h2>Change object details</h2>
    <?php endif;?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('entity_type_id'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('entity_type_id'))?>
        </div>        
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('code'))?>
        <div class="col-xs-4">
            <?php echo $this->formElement($form->get('code'))?>
        </div>        
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('name'))?>
        </div>        
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('description'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('description'))?>
        </div>        
    </div>
    <?php if(count($attributes) > 0): ?>
        <?php foreach ($attributes as $attribute):?>
            <?php
                switch($attribute->type) {
                    case 'textarea':
                        $width_class = 'col-xs-10';
                        break;
                    case 'text':
                        $width_class = 'col-xs-10';
                        break;
                    case 'boolean':
                        $width_class = 'col-xs-1';
                        break;
                    case 'integer':
                        $width_class = 'col-xs-2';
                        break;
                    case 'double':
                        $width_class = 'col-xs-2';
                        break;       
                    case 'select':
                        $width_class = 'col-xs-4';
                        break; 
                    default:
                        $width_class = 'col-xs-4';
                        break;
                }
            ?>            
            <div class="form-group">
                <?php echo $this->formLabel($form->get($attribute->code))?>
                <div class="<?php echo $width_class?>">
                    <?php echo $this->formElement($form->get($attribute->code))?>
                </div> 
            </div>            
        <?php endforeach;?>    
    <?php endif;?>
    
    <div class="form-group">
        <!--<label class="control-label col-xs-2" for="submit"></label>-->
        <div class="col-xs-offset-2 col-xs-2">            
            <?php echo $this->formElement($form->get('submit'))?>            
        </div>        
        <div class="col-xs-2">
            <button id='back' class="form-control">Back</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
</section>
<script>
$(document).ready(function() {
    $('#back').on('click', function(e) {
        window.location.href = '/pms/entity-definition';
    });
});
</script>

