<section class="entity-definition">
    <?php
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headLink()->appendStylesheet('/tablesorter-master/css/theme.metro-dark.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.js');
        $this->headScript()->appendFile('/tablesorter-master/js/jquery.tablesorter.widgets.js');
        $this->headScript()->appendFile('/tablesorter-master/js/widgets/widget-scroller.js');
        
        $entityDefinitions = $this->entityDefinitions;
    ?>
    <?php if($entityDefinitions == null || count($entityDefinitions) == 0):?>
        <h2>Error</h2>
        <p class="error">There are currently no defined object definitions.</p>
    <?php else:?>
        <h2>Object Definitions</h2>
        <p>
        <p>
        <table class="table tablesorter">
            <thead>
            <tr>
                <th>Type</th>
                <th>Code</th>
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($entityDefinitions as $entityDefinition):?>
                <tr>
                    <td>
                        <?php echo $entityDefinition['typename'] ?>
                    </td>
                    <td>
                        <?php echo $entityDefinition['code'] ?>
                    </td>
                    <td>
                        <?php echo $entityDefinition['name'] ?>
                    </td>
                    <td>
                        <?php echo $entityDefinition['description'] ?>
                    </td>
                    <td>
                        <a href="/pms/entity-definition/edit/<?php echo $entityDefinition['id']?>">Edit</a> | <a id="delete" href="/pms/entity-definition/delete/<?php echo $entityDefinition['id']?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    <?php endif; ?>
    <a href="/pms/entity-definition/new">Add new object definition</a> | <a href='/'>Home</a>
    <div hidden="true" id="ConfirmDialog" title="Delete Entity Definition?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0; font-size: 0.75em"></span>Definition will be completely deleted and cannot be recovered. Are you sure?</p>
    </div>
</section>
<script>
    $(document).ready(function(){
       $('.tablesorter').tablesorter({
            theme: 'metro-dark',
            showProcessing: true,
            headerTemplate : '{content} {icon}',
            widgets: [ 'columns', 'stickyHeaders', 'scroller' ],
            widgetOptions : {
                    scroller_height : 400,
                    // scroll tbody to top after sorting
                    scroller_upAfterSort: true,
                    // pop table header into view while scrolling up the page
                    scroller_jumpToHeader: true,
                    // In tablesorter v2.19.0 the scroll bar width is auto-detected
                    // add a value here to override the auto-detected setting
                    scroller_barWidth : null
                    // scroll_idPrefix was removed in v2.18.0
                    // scroller_idPrefix : 's_'
            }
        });
    });
    $('#ConfirmDialog').dialog({
        resizable: false,
        height:200,
        width:400,
        modal:true,
        autoOpen: false,
        modal:true,
        buttons : {
            "Yes" : function() {                
                $(this).dialog('close');             
                window.location.href = path;
            },
            "No" : function() {
                $(this).dialog('close');             
            }
        },
        close : function() {
            $(this).dialog('close');
        }
    });    
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        console.log(path);
        $('#ConfirmDialog').dialog('open');
    });
</script>