<section class="entity-definition-preview">
    <?php 
        $entityDefinitionModel = $this->model;
        $attributes = $this->attributes;
        $id = $this->id;        
    ?>
    <h3><?php echo $entityDefinitionModel->code?> parameters</h3>
    <!-- <table class="table" style="margin-left: 0px;padding-left: 0px"> -->
    <table class="table" id="att-table">
        <?php foreach($attributes as $attribute):?>
        <tr>
            <td><?php echo $attribute->label?></td>
            <td><?php 
                if($attribute->type == "boolean")
                {
                    echo $attribute->value ? 'Yes' : 'False';
                }
                else if($attribute->type == 'select')
                {
                    echo $attribute->getText();
                }
                else
                {
                    echo $attribute->value;
                }        
            ?></td>
            <td><?php echo $attribute->unit?></td>
        </tr>
        <?php endforeach;?>
    </table>
</section>
