<section class='user-manager-edit'>
    <?php
        $form = $this->form;
        $id = $this->user_id;

        $form->prepare();
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/user-manager', array(
                'action' => 'process',
                'id' => $id,
            )));  
        }
        else {
            $form->setAttribute('action', $this->url('pms/user-manager', array(
                'action' => 'process',
            ))); 
        }
        
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form);
    ?>
    <h2 class='page-header'>User Data</h2>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('role_id')); ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('role_id'));?>
        </div>
    </div>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('username')); ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('username'));?>
        </div>
    </div>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('email'));?>
        </div>
    </div>
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('password')); ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('password'));?>
        </div>
    </div>
    
    <div class='form-group'>
        <?php echo $this->formLabel($form->get('confirm_password')); ?>
        <div class='col-xs-4'>
            <?php echo $this->formElement($form->get('confirm_password'));?>
        </div>
    </div>
    
    <div class='form-group'>
        <div class='col-xs-offset-2 col-xs-2'>
            <?php                
                $submit = $form->get('submit');
                if(isset($id))
                {
                    $submit->setValue('Save');
                }                        
                echo $this->formElement($submit);
            ?>                        
        </div>
        <div class='col-xs-2'>
            <button class='form-control' id='back'>Back</button>
        </div>
    </div>        
    <?php echo $this->form()->closeTag() ?>
</section>
<script>
$(document).ready(function() {
    $('#back').on('click', function(e) {
        e.preventDefault();
        window.location.href='/';
    });
});
</script>
