<section class="user-manager">
    <?php
        $users = $this->users;        
    ?>
    <h2>Users</h2>
    <?php if(count($users) == 0):?>
    <p class="error">There are no users on the system.</p>
    <?php else: ?>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>E-Mail</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
        <?php foreach($users as $user):?>
        <tr>
            <td><?php echo $user['id']?></td>
            <td><?php echo $user['username']?></td>
            <td><?php echo $user['email']?></td>
            <td><?php echo $user['rolename']?></td>
            <td><a id='edit' href="/pms/user-manager/edit/<?php echo $user['id']?>">Edit</a> | <a id='delete' href="/pms/user-manager/delete/<?php echo $user['id']?>">Delete</a>
        </tr>
        <?php endforeach;?>
    </table>
    <?php endif;?>        
    <a href="/pms/user-manager/new">Add new user</a> | <a href='/'>Home</a>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Delete User</h4>
                    </button>
                </div>
                <div class="modal-body">
                    <p>User will be completely removed and can't be brought back. Are you sure?</p>
                </div>
                <div class='modal-footer'>
                    <button type='button' class='btn btn-confirm' data-dismiss='modal'>Yes</button>
                    <button type='button' class='btn btn-cancel' data-dismiss='modal'>No</button>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
$(document).ready(function() {
    var path;
    $('a#delete').on('click', function(e) {
        e.preventDefault();
        path = $(e.target).attr('href');
        $('#myModal').modal('show');                
    });
    
    $('.btn-confirm').on('click', function(e) {
        window.location.href=path;
    });
});  
</script>

