<section class="client-edit">
    <?php
        $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
        $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');          
        
        $form = $this->form;
        $id = $this->id;
        if(isset($id))
        {
            $form->setAttribute('action', $this->url('pms/client', [
                'action' => 'process',
                'id' => $id,
            ]));    
        }
        else {
            $form->setAttribute('action', $this->url('pms/client', [
                'action' => 'process',
            ]));
        }
        echo $this->form()->openTag($form);
        $this->headTitle("Client Details");
    ?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('title_id'))?>
        <div class="col-xs-1">
            <?php echo $this->formElement($form->get('title_id'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('first_name'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('first_name'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('last_name'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('last_name'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('address1'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('address1'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('address2'))?>
        <div class="col-xs-10">
            <?php echo $this->formElement($form->get('address2'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('city'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('city'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('zipcode'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('zipcode'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('country'))?>
        <div class="col-xs-3">
            <?php echo  $this->formElement($form->get('country'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('phone'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('phone'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('mobile'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('mobile'))?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('email'))?>
        <div class="col-xs-3">
            <?php echo $this->formElement($form->get('email'))?>
        </div>
    </div>
    <div class="form-group">        
        <div class="col-xs-offset-2 col-xs-2">
            <?php echo $this->formElement($form->get('submit'))?>
        </div>
        <div class="col-xs-2">
            <button id='back' class='form-control'>Back</button>
        </div>
    </div>        
    <?php echo $this->form()->closeTag()?>
</section>
<script>
 $(document).ready(function() {
     $('button#back').on('click', function(e) {
         window.location.href='/pms/client';
     })
 });    
</script>

