<?php 
    $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
    $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
    $this->headScript()->appendFile('/js/helper.js');
?>
<h2>Welcome to PMS Manager</h2>
<p>Our application is used to handle the reservations
    
<p><a class='ui-button' href="/pms/login">Sign In</a> 
<p> or <br>
<a class='ui-button' href="/pms/register">Sign Up</a>

