<?php 
    $this->headScript()->appendFile('/js/jquery-ui/jquery-ui.js');
    $this->headLink()->appendStylesheet('/js/jquery-ui/jquery-ui.css');
    $this->headScript()->appendFile('/js/helper.js');
?>
<h2 class="page-header">Welcome to PMS Manager</h2>
<p>Our application is used to handle the reservations

<p><a class='ui-button' href="/pms/login">Sign In</a> 
<p> or <br>
<a id="signup" class='ui-button' href="/pms/register">Sign Up</a>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Unsupported Action</h4>
            </div>
            <div class="modal-body">
                <p>Sorry! You can't do that automatically yet, please contact your system administrator in order to get the user account.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-confirm" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('#signup').on("click", function(e) {
        e.preventDefault();
        $('#myModal').modal('show');
    })
});
</script>