<h2>Welcome to PMS Manager</h2>
<p>Our application is used to handle the reservations
<p>Please <a href="/pms/login">sign in</a> or <a href="/pms/register">sign up as the new member</a>
<!--    
<h3>And here is the list of the current users:</h3>
<table class='table'>
    <tr>
        <th>
            Username
        </th>
        <th>
            E-mail
        </th>
    </tr>
    <?php foreach($users as $user) {?>
    <tr>
        <td>
            <?php echo $user->username ?>
        </td>
        <td>
            <?php echo $user->email ?>
        </td>
    </tr>
    <?php } ?>
</table>
-->
