<section class="admin">
    <h1>
        Welcome System Administrator 
    </h1>
    <p>Here, you can do following things...
    <h2>Entity Type Management</h2>
    <p>Entity types are the basic prototypes of reservation process objects, which are going to be dealt with in this presentation.
        You can add new ones or edit existing ones, or eventually delete them. <a href="/pms/entity-type">To entity type management >>> </a>
    <h2>Entity definition management</h2>
    <p>Entity types are further split to the subtypes, which are fitted to the potential client needs. These subtypes are called 'entity definitions'
       and except the basic set of parameters, can have an arbitrary set of parameters which can be added and deleted by you. This will be explained 
       by example: if an 'entity type' is a room, an 'entity definition' would be what kind of room it is - single, double, suite, de louxe single etc.
       By defining a set of parameters and setting of their values, you make the different entity definitions. In this section you can add the new ones
       and edit or delete existing ones. <a href='/pms/entity-definition'>To entity definitions management >>> </a>
    <h2>Attribute Management</h2>
    <p>Attributes are the parameter objects which can be associated with the different entity definitions or entities. An attribute basically consists name, 
        datatype and value. Here, you can add new and edit or delete the existing ones. <a href='/pms/attribute-manager'>To attribute management >>> </a>
    <h2>User management</h2>
    <p>As administrator, you have the possibility to add and delete the application users. <a href='/pms/user-manager'>To user management >>>> </a>
</section>

