<sectio class="register">
    <h2>Register</h2>
    <?php if($this->error): ?>
        <p class="error">
            There has been an error on submitting data. Please correct these errors, 
            as indicated bellow.
        </p>
    <?php endif;?>
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, ['controller' => 'register', 'action' => 'process']));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form);
    ?>
    <dl class='zend_form'>
        <dt><?php echo $this->formLabel($form->get('role_id')); ?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('role_id'));
                echo $this->formElementErrors($form->get('role_id'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('username')) ?></dt>
        <dd><?php
            echo $this->formElement($form->get('username'));
            echo $this->formElementErrors($form->get('username'));
        ?></dd>
        <dt><?php echo $this->formLabel($form->get('email')) ?></dt>
        <dd><?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
        ?></dd>
        <dt><?php echo $this->formLabel($form->get('password'));?></dt>
        <dd><?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
        ?></dd>
        <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
        ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
        ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>

